apiVersion: apps/v1
kind: Deployment
metadata:
  name: [LOCUST-WORKER-NAME]
  labels:
    name: [LOCUST-WORKER-NAME]
spec:
  replicas: 1
  selector:
    matchLabels:
      app: [LOCUST-WORKER-NAME]
  template:
    metadata:
      labels:
        app: [LOCUST-WORKER-NAME]
    spec:
      containers:
        - name: [LOCUST-WORKER-NAME]
          image: gcr.io/[PROJECT_ID]/locust-tasks
          imagePullPolicy: Always
          resources:
            limits:
              cpu: "1"
              memory: 1000Mi
            requests:
              cpu: "1"
              memory: 1000Mi
          env:
            - name: LOCUST_MODE
              value: worker
            - name: LOCUST_MASTER
              value: locust-master
            - name: TARGET_HOST
              value: [TARGET_HOST]
            - name: RABBITMQ_URL
              value: [RABBITMQ_CONNECTION]
            - name: INSTANCE_NUM
              value: "[INSTANCE_NUM]"
            - name: MAX_INSTANCES
              value: "[MAX_INSTANCES]"
